### ISSUE TITLE
Migrate to lintPublish

### ISSUE THREAD

**Issue by ColtonIdle** [saurabharora90/Lint-Checks#1]
https://developer.android.com/studio/releases/gradle-plugin#3-4-0

If you try to use your library + your own lint check module the build fails. Apparently this is due to a change where library projects should be using lintPublish?

> lintPublish: Use this new configuration in library projects for lint checks you want to include in the published AAR, as shown below. This means that projects that consume your library also apply those lint checks.

**Comment by saurabharora90** [comment]
Thanks for raising this.

Will investigate and update here

**Comment by saurabharora90** [comment]
Given that there is no library involved here and these are just lint checks, I don't see why we would need to migrate to `lintPublish`. `lintChecks` should be sufficient as you only need to include the checks and not any library

**Comment by ColtonIdle** [comment]
Not sure. All I know is that I tried to use a custom lint check + `saurabharora90/Lint-Checks` in the same app, and it doesn't work. If I removed this library lint check, then my custom lint checks work.

**Comment by saurabharora90** [comment]
Do you have a detailed error log? Or how are you including your custom lint check along with this one?

**Comment by saurabharora90** [comment]
Seems like this is a bug and the AS team is on it. We'll probably have to wait for them to fix it

https://issuetracker.google.com/issues/141840950

**Comment by ColtonIdle** [comment]
I just followed the video and GitHub repo from the Android Dev Summit 2019 on lint checks.
https://youtu.be/jCmJWOkjbM0

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by saurabharora90** [comment]
Seems like this is a bug and the AS team is on it. We'll probably have to wait for them to fix it

https://issuetracker.google.com/issues/141840950
