### ISSUE TITLE
Request: have it as official addon for IDE Lint?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [saurabharora90/Lint-Checks#2]
Is it possible?
If so, please do add it. Could be nice...

**Comment by saurabharora90** [comment]
Can you elaborate on this? Did you mean that it becomes a part of the standard lint checks out of the box?

**Comment by AndroidDeveloperLB** [comment]
Yes. Via this menu item:

![image](https://user-images.githubusercontent.com/5357526/69329536-f7f6f100-0c59-11ea-90a6-180a25b5e268.png)

Is it even possible?

**Comment by saurabharora90** [comment]
I don't really think this is possible. With the library, you'll get hints in the IDE directly while writing code.

**Comment by AndroidDeveloperLB** [comment]
Too bad. Can you please show a screenshot/video of this though? Maybe even put it on the repositories page?
