### ISSUE TITLE
Migration to mavenCentral

### ISSUE THREAD

**Issue by jolaf** [saurabharora90/Lint-Checks#3]
For now, this library is available from jCenter repository, which is being deprecated:
http://developer.android.com/r/tools/jcenter-end-of-service

It would be nice to migrate it to mavenCentral() to be used further.

**Comment by saurabharora90** [comment]
Yes. I have it on the roadmap.

Unfortunately I am dealing with a lot right now given the COVID crisis in India. Once things settle down, I'll work on it.

**Comment by jolaf** [comment]
Best health to you, your colleagues, friends and relatives, and everybody in India!

**Comment by jolaf** [comment]
Hi!
Hope you are well.
Is there a chance to move on with this?

**Comment by saurabharora90** [comment]
Thank you for bringing it to my notice again. I'll work on this over the weekend and update :)

**Comment by jolaf** [comment]
Cool, thanks!

**Comment by saurabharora90** [comment]
Released. Usage is the same but the package name has been changed. Have a look at the updated guide: https://github.com/saurabharora90/Lint-Checks/tree/master/dark-theme-lint

**Comment by jolaf** [comment]
Great, thank you very much!
